apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "gooddatasp.name" . }}
{{- include "gooddatasp.labels" . | nindent 4 }}
  name: {{ template "gooddatasp.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "gooddatasp.name" . }}
  template:
    metadata:
      annotations:
      labels:
        app: {{ template "gooddatasp.name" . }}
{{- include "gooddatasp.labels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- if .Values.dockerRegistrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecretName }}
      {{- end}}
      volumes:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5002
              protocol: TCP
          {{- if .Values.securityContext }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GOODDATA_HOST
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: GOODDATA_HOST
            - name: GOODDATA_TOKEN
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: GOODDATA_TOKEN
            - name: SNOWFLAKE_USER
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: SNOWFLAKE_USER
            - name: SNOWFLAKE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: SNOWFLAKE_PASSWORD
            - name: SNOWFLAKE_ROLE
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: SNOWFLAKE_ROLE
            - name: SNOWFLAKE_ORGANIZATION_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: SNOWFLAKE_ORGANIZATION_ACCOUNT
            - name: SNOWFLAKE_WAREHOUSE
              valueFrom:
                secretKeyRef:
                  name: witboost-addons-secrets
                  key: SNOWFLAKE_WAREHOUSE
          volumeMounts:
